Test API project for Lesson 12
eugene-okulik/romanert pull request #20
Opened 2024-08-30 05:19 UTC by RomanErt

2024-08-30 08:06 UTC, eugene-okulik requested changes
Очень хорошо, но есть небольшая путаница в названиях и пара тестов - без проверок. У каждого теста есть ожидаемый результат и автотесты - не исключение.

2024-08-30 08:06 UTC, eugene-okulik commented on test_api_romanert/tests/test_jsph.py
jsph (jsonplaceholder) - это название той апишки, которую я демонстрировал в видео. Здесь ты тестируешь другую апи.  Названия важны.

2024-08-30 08:06 UTC, eugene-okulik commented on test_api_romanert/endpoints/create_post.py
> +class CreatePost(Endpoint):
В этой апи мы создаем не посты, а объекты. Это в той апишке, что была на занятии была типа апишка соцсети, а в соцсетях посты.

2024-08-30 08:06 UTC, eugene-okulik commented on test_api_romanert/tests/test_jsph.py
> +    delete_post_endpoint.delete_post(post_id=create_post_endpoint.post_id)
В этом тесте нет проверки. В любом тесте должно что-то проверяться.

2024-08-30 08:06 UTC, eugene-okulik commented on test_api_romanert/tests/test_jsph.py
> +    update_post_patch_endpoint.update_post_patch(post_id=create_post_endpoint.post_id, body=body)
И в этом тесте нет проверки

2024-08-31 01:13 UTC, RomanErt commented on test_api_romanert/tests/test_jsph.py
> +    update_post_patch_endpoint.update_post_patch(post_id=create_post_endpoint.post_id, body=body)
Всё пофиксил

2024-08-31 10:30 UTC, eugene-okulik approved these changes

2024-08-31 10:31 UTC, merged